codecov:
  token: 34e2cf29-5d59-42d5-a09e-7b32502db9dc
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
